//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIPC22011903872.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCUENTRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENCUENTRO()
        {
            this.PARTIDA_TORNEO = new HashSet<PARTIDA_TORNEO>();
        }
    
        public int Codigo_Encuentro { get; set; }
        public int Codigo_Equipo1 { get; set; }
        public int Codigo_Equipo2 { get; set; }
        public int Numero_Fase { get; set; }
        public string Ganador { get; set; }
        public int Punteo_Equipo1 { get; set; }
        public int Punteo_Equipo2 { get; set; }
    
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual EQUIPO EQUIPO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIDA_TORNEO> PARTIDA_TORNEO { get; set; }
    }
}
