//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIPC22011903872.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQUIPO()
        {
            this.ENCUENTRO = new HashSet<ENCUENTRO>();
            this.ENCUENTRO1 = new HashSet<ENCUENTRO>();
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int Codigo_Equipo { get; set; }
        public int Codigo_Torneo { get; set; }
        public string Nombre { get; set; }
        public int PUNTEO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENCUENTRO> ENCUENTRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENCUENTRO> ENCUENTRO1 { get; set; }
        public virtual TORNEO TORNEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
